version: '3.9'

networks:
  net:
    driver: bridge
services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ./chromadb:/data
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000
    networks:
      - net